version: "3.4"
services:

  keepassshtokal:
    
    image: ${DOCKER_REGISTRY-}keepassshtokal
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: KeePassShtokal/Dockerfile