version: "3.4"
services:

  mssql-server:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      SA_PASSWORD: "pass"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-volume:/var/opt/sqlserver
    ports:
      - "1433:1433"

  keepassshtokal:
    image: ${DOCKER_REGISTRY-}keepassshtokal
    build:
      context: .
      dockerfile: KeePassShtokal/Dockerfile
    depends_on:
      - mssql-server
volumes:
  mssql-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'DOCKER_VOLUMES/KeepPassMsSQL'